<?php
/* vim: set expandtab tabstop=4 shiftwidth=4: */
/**
 *
 * $Id: sdif.forms.class.php 858 2012-05-11 03:07:23Z mpwalsh8 $
 *
 * Plugin initialization.  This code will ensure that the
 * include_path is correct for phpHtmlLib, PEAR, and the local
 * site class and include files.
 *
 * (c) 2007 by Mike Walsh
 *
 * @author Mike Walsh <mike_walsh@mindspring.com>
 * @package Wp-SwimTeam
 * @subpackage SDIFProfile
 * @version $Revision: 858 $
 * @lastmodified $Author: mpwalsh8 $
 * @lastmodifiedby $Date: 2012-05-10 23:07:23 -0400 (Thu, 10 May 2012) $
 *
 */

require_once("sdif.include.php") ;
require_once("sdif.class.php") ;
require_once("forms.class.php") ;

/**
 * Construct the Add Age Group form
 *
 * @author Mike Walsh <mike_walsh@mindspring.com>
 * @access public
 * @see WpSwimTeamForm
 */
class WpSwimTeamSDIFProfileForm extends WpSwimTeamForm
{
    /**
     * This method gets called EVERY time the object is
     * created.  It is used to build all of the 
     * FormElement objects used in this Form.
     *
     */
    function form_init_elements()
    {
        $this->add_hidden_element("UserId") ;
        $geography = get_option(WPST_OPTION_GEOGRAPHY) ;

        $orgcode = new FEListBox("Org Code", true, "200px");
        $orgcode->set_list_data(array(
            WPST_SDIF_ORG_CODE_USS_LABEL => WPST_SDIF_ORG_CODE_USS_VALUE
           ,WPST_SDIF_ORG_CODE_MASTERS_LABEL => WPST_SDIF_ORG_CODE_MASTERS_VALUE
           ,WPST_SDIF_ORG_CODE_NCAA_LABEL => WPST_SDIF_ORG_CODE_NCAA_VALUE
           ,WPST_SDIF_ORG_CODE_NCAA_DIV_I_LABEL => WPST_SDIF_ORG_CODE_NCAA_DIV_I_VALUE
           ,WPST_SDIF_ORG_CODE_NCAA_DIV_II_LABEL => WPST_SDIF_ORG_CODE_NCAA_DIV_II_VALUE
           ,WPST_SDIF_ORG_CODE_NCAA_DIV_III_LABEL => WPST_SDIF_ORG_CODE_NCAA_DIV_III_VALUE
           ,WPST_SDIF_ORG_CODE_YMCA_LABEL => WPST_SDIF_ORG_CODE_YMCA_VALUE
           ,WPST_SDIF_ORG_CODE_FINA_LABEL => WPST_SDIF_ORG_CODE_FINA_VALUE
           ,WPST_SDIF_ORG_CODE_HIGH_SCHOOL_LABEL => WPST_SDIF_ORG_CODE_HIGH_SCHOOL_VALUE
        )) ;
        $this->add_element($orgcode) ;

        $teamcode = new FEText("Team Code", true, "200px") ;
        $this->add_element($teamcode) ;

        $lsccode = new FEListBox("LSC Code", true, "200px");
        $lsccode->set_list_data(array(
            WPST_SDIF_LSC_CODE_ADIRONDACK_LABEL => WPST_SDIF_LSC_CODE_ADIRONDACK_VALUE
           ,WPST_SDIF_LSC_CODE_ALASKA_LABEL => WPST_SDIF_LSC_CODE_ALASKA_VALUE
           ,WPST_SDIF_LSC_CODE_ALLEGHENY_MOUNTAIN_LABEL => WPST_SDIF_LSC_CODE_ALLEGHENY_MOUNTAIN_VALUE
           ,WPST_SDIF_LSC_CODE_ARKANSAS_LABEL => WPST_SDIF_LSC_CODE_ARKANSAS_VALUE
           ,WPST_SDIF_LSC_CODE_ARIZONA_LABEL => WPST_SDIF_LSC_CODE_ARIZONA_VALUE
           ,WPST_SDIF_LSC_CODE_BORDER_LABEL => WPST_SDIF_LSC_CODE_BORDER_VALUE
           ,WPST_SDIF_LSC_CODE_CENTRAL_CALIFORNIA_LABEL => WPST_SDIF_LSC_CODE_CENTRAL_CALIFORNIA_VALUE
           ,WPST_SDIF_LSC_CODE_COLORADO_LABEL => WPST_SDIF_LSC_CODE_COLORADO_VALUE
           ,WPST_SDIF_LSC_CODE_CONNECTICUT_LABEL => WPST_SDIF_LSC_CODE_CONNECTICUT_VALUE
           ,WPST_SDIF_LSC_CODE_FLORIDA_GOLD_COAST_LABEL => WPST_SDIF_LSC_CODE_FLORIDA_GOLD_COAST_VALUE
           ,WPST_SDIF_LSC_CODE_FLORIDA_LABEL => WPST_SDIF_LSC_CODE_FLORIDA_VALUE
           ,WPST_SDIF_LSC_CODE_GEORGIA_LABEL => WPST_SDIF_LSC_CODE_GEORGIA_VALUE
           ,WPST_SDIF_LSC_CODE_GULF_LABEL => WPST_SDIF_LSC_CODE_GULF_VALUE
           ,WPST_SDIF_LSC_CODE_HAWAII_LABEL => WPST_SDIF_LSC_CODE_HAWAII_VALUE
           ,WPST_SDIF_LSC_CODE_IOWA_LABEL => WPST_SDIF_LSC_CODE_IOWA_VALUE
           ,WPST_SDIF_LSC_CODE_INLAND_EMPIRE_LABEL => WPST_SDIF_LSC_CODE_INLAND_EMPIRE_VALUE
           ,WPST_SDIF_LSC_CODE_ILLINOIS_LABEL => WPST_SDIF_LSC_CODE_ILLINOIS_VALUE
           ,WPST_SDIF_LSC_CODE_INDIANA_LABEL => WPST_SDIF_LSC_CODE_INDIANA_VALUE
           ,WPST_SDIF_LSC_CODE_KENTUCKY_LABEL => WPST_SDIF_LSC_CODE_KENTUCKY_VALUE
           ,WPST_SDIF_LSC_CODE_LOUISIANA_LABEL => WPST_SDIF_LSC_CODE_LOUISIANA_VALUE
           ,WPST_SDIF_LSC_CODE_LAKE_ERIE_LABEL => WPST_SDIF_LSC_CODE_LAKE_ERIE_VALUE
           ,WPST_SDIF_LSC_CODE_MIDDLE_ATLANTIC_LABEL => WPST_SDIF_LSC_CODE_MIDDLE_ATLANTIC_VALUE
           ,WPST_SDIF_LSC_CODE_MARYLAND_LABEL => WPST_SDIF_LSC_CODE_MARYLAND_VALUE
           ,WPST_SDIF_LSC_CODE_MAINE_LABEL => WPST_SDIF_LSC_CODE_MAINE_VALUE
           ,WPST_SDIF_LSC_CODE_MINNESOTA_LABEL => WPST_SDIF_LSC_CODE_MINNESOTA_VALUE
           ,WPST_SDIF_LSC_CODE_MICHIGAN_LABEL => WPST_SDIF_LSC_CODE_MICHIGAN_VALUE
           ,WPST_SDIF_LSC_CODE_METROPOLITAN_LABEL => WPST_SDIF_LSC_CODE_METROPOLITAN_VALUE
           ,WPST_SDIF_LSC_CODE_MISSISSIPPI_LABEL => WPST_SDIF_LSC_CODE_MISSISSIPPI_VALUE
           ,WPST_SDIF_LSC_CODE_MONTANA_LABEL => WPST_SDIF_LSC_CODE_MONTANA_VALUE
           ,WPST_SDIF_LSC_CODE_MISSOURI_VALLEY_LABEL => WPST_SDIF_LSC_CODE_MISSOURI_VALLEY_VALUE
           ,WPST_SDIF_LSC_CODE_MIDWESTERN_LABEL => WPST_SDIF_LSC_CODE_MIDWESTERN_VALUE
           ,WPST_SDIF_LSC_CODE_NORTH_CAROLINA_LABEL => WPST_SDIF_LSC_CODE_NORTH_CAROLINA_VALUE
           ,WPST_SDIF_LSC_CODE_NORTH_DAKOTA_LABEL => WPST_SDIF_LSC_CODE_NORTH_DAKOTA_VALUE
           ,WPST_SDIF_LSC_CODE_NEW_ENGLAND_LABEL => WPST_SDIF_LSC_CODE_NEW_ENGLAND_VALUE
           ,WPST_SDIF_LSC_CODE_NIAGARA_LABEL => WPST_SDIF_LSC_CODE_NIAGARA_VALUE
           ,WPST_SDIF_LSC_CODE_NEW_JERSEY_LABEL => WPST_SDIF_LSC_CODE_NEW_JERSEY_VALUE
           ,WPST_SDIF_LSC_CODE_NEW_MEXICO_LABEL => WPST_SDIF_LSC_CODE_NEW_MEXICO_VALUE
           ,WPST_SDIF_LSC_CODE_NORTH_TEXAS_LABEL => WPST_SDIF_LSC_CODE_NORTH_TEXAS_VALUE
           ,WPST_SDIF_LSC_CODE_OHIO_LABEL => WPST_SDIF_LSC_CODE_OHIO_VALUE
           ,WPST_SDIF_LSC_CODE_OKLAHOMA_LABEL => WPST_SDIF_LSC_CODE_OKLAHOMA_VALUE
           ,WPST_SDIF_LSC_CODE_OREGON_LABEL => WPST_SDIF_LSC_CODE_OREGON_VALUE
           ,WPST_SDIF_LSC_CODE_OZARK_LABEL => WPST_SDIF_LSC_CODE_OZARK_VALUE
           ,WPST_SDIF_LSC_CODE_PACIFIC_LABEL => WPST_SDIF_LSC_CODE_PACIFIC_VALUE
           ,WPST_SDIF_LSC_CODE_PACIFIC_NORTHWEST_LABEL => WPST_SDIF_LSC_CODE_PACIFIC_NORTHWEST_VALUE
           ,WPST_SDIF_LSC_CODE_POTOMAC_VALLEY_LABEL => WPST_SDIF_LSC_CODE_POTOMAC_VALLEY_VALUE
           ,WPST_SDIF_LSC_CODE_SOUTH_CAROLINA_LABEL => WPST_SDIF_LSC_CODE_SOUTH_CAROLINA_VALUE
           ,WPST_SDIF_LSC_CODE_SOUTH_DAKOTA_LABEL => WPST_SDIF_LSC_CODE_SOUTH_DAKOTA_VALUE
           ,WPST_SDIF_LSC_CODE_SOUTHEASTERN_LABEL => WPST_SDIF_LSC_CODE_SOUTHEASTERN_VALUE
           ,WPST_SDIF_LSC_CODE_SOUTHERN_CALIFORNIA_LABEL => WPST_SDIF_LSC_CODE_SOUTHERN_CALIFORNIA_VALUE
           ,WPST_SDIF_LSC_CODE_SAN_DIEGO_IMPERIAL_LABEL => WPST_SDIF_LSC_CODE_SAN_DIEGO_IMPERIAL_VALUE
           ,WPST_SDIF_LSC_CODE_WEST_TEXAS_LABEL => WPST_SDIF_LSC_CODE_WEST_TEXAS_VALUE
           ,WPST_SDIF_LSC_CODE_SIERRA_NEVADA_LABEL => WPST_SDIF_LSC_CODE_SIERRA_NEVADA_VALUE
           ,WPST_SDIF_LSC_CODE_SNAKE_RIVER_LABEL => WPST_SDIF_LSC_CODE_SNAKE_RIVER_VALUE
           ,WPST_SDIF_LSC_CODE_SOUTH_TEXAS_LABEL => WPST_SDIF_LSC_CODE_SOUTH_TEXAS_VALUE
           ,WPST_SDIF_LSC_CODE_UTAH_LABEL => WPST_SDIF_LSC_CODE_UTAH_VALUE
           ,WPST_SDIF_LSC_CODE_VIRGINIA_LABEL => WPST_SDIF_LSC_CODE_VIRGINIA_VALUE
           ,WPST_SDIF_LSC_CODE_WISCONSIN_LABEL => WPST_SDIF_LSC_CODE_WISCONSIN_VALUE
           ,WPST_SDIF_LSC_CODE_WEST_VIRGINIA_LABEL => WPST_SDIF_LSC_CODE_WEST_VIRGINIA_VALUE
           ,WPST_SDIF_LSC_CODE_WYOMING_LABEL => WPST_SDIF_LSC_CODE_WYOMING_VALUE
            
        )) ;
        $this->add_element($lsccode) ;

        $countrycode = new FEListBox("Country Code", true, "200px");
        $countrycode->set_list_data(array(
            WPST_SDIF_COUNTRY_CODE_AFGHANISTAN_LABEL => WPST_SDIF_COUNTRY_CODE_AFGHANISTAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ALBANIA_LABEL => WPST_SDIF_COUNTRY_CODE_ALBANIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ALGERIA_LABEL => WPST_SDIF_COUNTRY_CODE_ALGERIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_AMERICAN_SAMOA_LABEL => WPST_SDIF_COUNTRY_CODE_AMERICAN_SAMOA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ANDORRA_LABEL => WPST_SDIF_COUNTRY_CODE_ANDORRA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ANGOLA_LABEL => WPST_SDIF_COUNTRY_CODE_ANGOLA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ANTIGUA_LABEL => WPST_SDIF_COUNTRY_CODE_ANTIGUA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ANTILLES_NETHERLANDS_DUTCH_WEST_INDIES_LABEL => WPST_SDIF_COUNTRY_CODE_ANTILLES_NETHERLANDS_DUTCH_WEST_INDIES_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ARAB_REPUBLIC_OF_EGYPT_LABEL => WPST_SDIF_COUNTRY_CODE_ARAB_REPUBLIC_OF_EGYPT_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ARGENTINA_LABEL => WPST_SDIF_COUNTRY_CODE_ARGENTINA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ARMENIA_LABEL => WPST_SDIF_COUNTRY_CODE_ARMENIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ARUBA_LABEL => WPST_SDIF_COUNTRY_CODE_ARUBA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_AUSTRALIA_LABEL => WPST_SDIF_COUNTRY_CODE_AUSTRALIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_AUSTRIA_LABEL => WPST_SDIF_COUNTRY_CODE_AUSTRIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_AZERBAIJAN_LABEL => WPST_SDIF_COUNTRY_CODE_AZERBAIJAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BAHAMAS_LABEL => WPST_SDIF_COUNTRY_CODE_BAHAMAS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BAHRAIN_LABEL => WPST_SDIF_COUNTRY_CODE_BAHRAIN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BANGLADESH_LABEL => WPST_SDIF_COUNTRY_CODE_BANGLADESH_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BARBADOS_LABEL => WPST_SDIF_COUNTRY_CODE_BARBADOS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BELARUS_LABEL => WPST_SDIF_COUNTRY_CODE_BELARUS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BELGIUM_LABEL => WPST_SDIF_COUNTRY_CODE_BELGIUM_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BELIZE_LABEL => WPST_SDIF_COUNTRY_CODE_BELIZE_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BENIN_LABEL => WPST_SDIF_COUNTRY_CODE_BENIN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BERMUDA_LABEL => WPST_SDIF_COUNTRY_CODE_BERMUDA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BHUTAN_LABEL => WPST_SDIF_COUNTRY_CODE_BHUTAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BOLIVIA_LABEL => WPST_SDIF_COUNTRY_CODE_BOLIVIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BOTSWANA_LABEL => WPST_SDIF_COUNTRY_CODE_BOTSWANA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BRAZIL_LABEL => WPST_SDIF_COUNTRY_CODE_BRAZIL_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BRITISH_VIRGIN_ISLANDS_LABEL => WPST_SDIF_COUNTRY_CODE_BRITISH_VIRGIN_ISLANDS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BRUNEI_LABEL => WPST_SDIF_COUNTRY_CODE_BRUNEI_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BULGARIA_LABEL => WPST_SDIF_COUNTRY_CODE_BULGARIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_BURKINA_FASO_LABEL => WPST_SDIF_COUNTRY_CODE_BURKINA_FASO_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CAMEROON_LABEL => WPST_SDIF_COUNTRY_CODE_CAMEROON_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CANADA_LABEL => WPST_SDIF_COUNTRY_CODE_CANADA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CAYMAN_ISLANDS_LABEL => WPST_SDIF_COUNTRY_CODE_CAYMAN_ISLANDS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CENTRAL_AFRICAN_REPUBLIC_LABEL => WPST_SDIF_COUNTRY_CODE_CENTRAL_AFRICAN_REPUBLIC_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CHAD_LABEL => WPST_SDIF_COUNTRY_CODE_CHAD_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CHILE_LABEL => WPST_SDIF_COUNTRY_CODE_CHILE_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CHINESE_TAIPEI_LABEL => WPST_SDIF_COUNTRY_CODE_CHINESE_TAIPEI_VALUE
           ,WPST_SDIF_COUNTRY_CODE_COLUMBIA_LABEL => WPST_SDIF_COUNTRY_CODE_COLUMBIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_COOK_ISLANDS_LABEL => WPST_SDIF_COUNTRY_CODE_COOK_ISLANDS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_COSTA_RICA_LABEL => WPST_SDIF_COUNTRY_CODE_COSTA_RICA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CROATIA_LABEL => WPST_SDIF_COUNTRY_CODE_CROATIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CUBA_LABEL => WPST_SDIF_COUNTRY_CODE_CUBA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CYPRUS_LABEL => WPST_SDIF_COUNTRY_CODE_CYPRUS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_CZECHOSLOVAKIA_LABEL => WPST_SDIF_COUNTRY_CODE_CZECHOSLOVAKIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_DEMOCRATIC_PEOPLES_REP_OF_KOREA_LABEL => WPST_SDIF_COUNTRY_CODE_DEMOCRATIC_PEOPLES_REP_OF_KOREA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_DENMARK_LABEL => WPST_SDIF_COUNTRY_CODE_DENMARK_VALUE
           ,WPST_SDIF_COUNTRY_CODE_DJIBOUTI_LABEL => WPST_SDIF_COUNTRY_CODE_DJIBOUTI_VALUE
           ,WPST_SDIF_COUNTRY_CODE_DOMINICAN_REPUBLIC_LABEL => WPST_SDIF_COUNTRY_CODE_DOMINICAN_REPUBLIC_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ECUADOR_LABEL => WPST_SDIF_COUNTRY_CODE_ECUADOR_VALUE
           ,WPST_SDIF_COUNTRY_CODE_EL_SALVADOR_LABEL => WPST_SDIF_COUNTRY_CODE_EL_SALVADOR_VALUE
           ,WPST_SDIF_COUNTRY_CODE_EQUATORIAL_GUINEA_LABEL => WPST_SDIF_COUNTRY_CODE_EQUATORIAL_GUINEA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ESTONIA_LABEL => WPST_SDIF_COUNTRY_CODE_ESTONIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ETHIOPIA_LABEL => WPST_SDIF_COUNTRY_CODE_ETHIOPIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_FIJI_LABEL => WPST_SDIF_COUNTRY_CODE_FIJI_VALUE
           ,WPST_SDIF_COUNTRY_CODE_FINLAND_LABEL => WPST_SDIF_COUNTRY_CODE_FINLAND_VALUE
           ,WPST_SDIF_COUNTRY_CODE_FRANCE_LABEL => WPST_SDIF_COUNTRY_CODE_FRANCE_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GABON_LABEL => WPST_SDIF_COUNTRY_CODE_GABON_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GAMBIA_LABEL => WPST_SDIF_COUNTRY_CODE_GAMBIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GEORGIA_LABEL => WPST_SDIF_COUNTRY_CODE_GEORGIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GERMANY_LABEL => WPST_SDIF_COUNTRY_CODE_GERMANY_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GHANA_LABEL => WPST_SDIF_COUNTRY_CODE_GHANA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GREAT_BRITAIN_LABEL => WPST_SDIF_COUNTRY_CODE_GREAT_BRITAIN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GREECE_LABEL => WPST_SDIF_COUNTRY_CODE_GREECE_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GRENADA_LABEL => WPST_SDIF_COUNTRY_CODE_GRENADA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GUAM_LABEL => WPST_SDIF_COUNTRY_CODE_GUAM_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GUATEMALA_LABEL => WPST_SDIF_COUNTRY_CODE_GUATEMALA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GUINEA_LABEL => WPST_SDIF_COUNTRY_CODE_GUINEA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_GUYANA_LABEL => WPST_SDIF_COUNTRY_CODE_GUYANA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_HAITI_LABEL => WPST_SDIF_COUNTRY_CODE_HAITI_VALUE
           ,WPST_SDIF_COUNTRY_CODE_HONDURAS_LABEL => WPST_SDIF_COUNTRY_CODE_HONDURAS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_HONG_KONG_LABEL => WPST_SDIF_COUNTRY_CODE_HONG_KONG_VALUE
           ,WPST_SDIF_COUNTRY_CODE_HUNGARY_LABEL => WPST_SDIF_COUNTRY_CODE_HUNGARY_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ICELAND_LABEL => WPST_SDIF_COUNTRY_CODE_ICELAND_VALUE
           ,WPST_SDIF_COUNTRY_CODE_INDIA_LABEL => WPST_SDIF_COUNTRY_CODE_INDIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_INDONESIA_LABEL => WPST_SDIF_COUNTRY_CODE_INDONESIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_IRAQ_LABEL => WPST_SDIF_COUNTRY_CODE_IRAQ_VALUE
           ,WPST_SDIF_COUNTRY_CODE_IRELAND_LABEL => WPST_SDIF_COUNTRY_CODE_IRELAND_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ISLAMIC_REP_OF_IRAN_LABEL => WPST_SDIF_COUNTRY_CODE_ISLAMIC_REP_OF_IRAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ISRAEL_LABEL => WPST_SDIF_COUNTRY_CODE_ISRAEL_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ITALY_LABEL => WPST_SDIF_COUNTRY_CODE_ITALY_VALUE
           ,WPST_SDIF_COUNTRY_CODE_IVORY_COAST_LABEL => WPST_SDIF_COUNTRY_CODE_IVORY_COAST_VALUE
           ,WPST_SDIF_COUNTRY_CODE_JAMAICA_LABEL => WPST_SDIF_COUNTRY_CODE_JAMAICA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_JAPAN_LABEL => WPST_SDIF_COUNTRY_CODE_JAPAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_JORDAN_LABEL => WPST_SDIF_COUNTRY_CODE_JORDAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_KAZAKHSTAN_LABEL => WPST_SDIF_COUNTRY_CODE_KAZAKHSTAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_KENYA_LABEL => WPST_SDIF_COUNTRY_CODE_KENYA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_KOREA_SOUTH_LABEL => WPST_SDIF_COUNTRY_CODE_KOREA_SOUTH_VALUE
           ,WPST_SDIF_COUNTRY_CODE_KUWAIT_LABEL => WPST_SDIF_COUNTRY_CODE_KUWAIT_VALUE
           ,WPST_SDIF_COUNTRY_CODE_KYRGHYZSTAN_LABEL => WPST_SDIF_COUNTRY_CODE_KYRGHYZSTAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_LAOS_LABEL => WPST_SDIF_COUNTRY_CODE_LAOS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_LATVIA_LABEL => WPST_SDIF_COUNTRY_CODE_LATVIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_LEBANON_LABEL => WPST_SDIF_COUNTRY_CODE_LEBANON_VALUE
           ,WPST_SDIF_COUNTRY_CODE_LESOTHO_LABEL => WPST_SDIF_COUNTRY_CODE_LESOTHO_VALUE
           ,WPST_SDIF_COUNTRY_CODE_LIBERIA_LABEL => WPST_SDIF_COUNTRY_CODE_LIBERIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_LIBYA_LABEL => WPST_SDIF_COUNTRY_CODE_LIBYA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_LIECHTENSTEIN_LABEL => WPST_SDIF_COUNTRY_CODE_LIECHTENSTEIN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_LITHUANIA_LABEL => WPST_SDIF_COUNTRY_CODE_LITHUANIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_LUXEMBOURG_LABEL => WPST_SDIF_COUNTRY_CODE_LUXEMBOURG_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MADAGASCAR_LABEL => WPST_SDIF_COUNTRY_CODE_MADAGASCAR_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MALAWI_LABEL => WPST_SDIF_COUNTRY_CODE_MALAWI_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MALAYSIA_LABEL => WPST_SDIF_COUNTRY_CODE_MALAYSIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MALDIVES_LABEL => WPST_SDIF_COUNTRY_CODE_MALDIVES_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MALI_LABEL => WPST_SDIF_COUNTRY_CODE_MALI_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MALTA_LABEL => WPST_SDIF_COUNTRY_CODE_MALTA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MAURITANIA_LABEL => WPST_SDIF_COUNTRY_CODE_MAURITANIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MAURITIUS_LABEL => WPST_SDIF_COUNTRY_CODE_MAURITIUS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MEXICO_LABEL => WPST_SDIF_COUNTRY_CODE_MEXICO_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MOLDOVA_LABEL => WPST_SDIF_COUNTRY_CODE_MOLDOVA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MONACO_LABEL => WPST_SDIF_COUNTRY_CODE_MONACO_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MONGOLIA_LABEL => WPST_SDIF_COUNTRY_CODE_MONGOLIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MOROCCO_LABEL => WPST_SDIF_COUNTRY_CODE_MOROCCO_VALUE
           ,WPST_SDIF_COUNTRY_CODE_MOZAMBIQUE_LABEL => WPST_SDIF_COUNTRY_CODE_MOZAMBIQUE_VALUE
           ,WPST_SDIF_COUNTRY_CODE_NAMIBIA_LABEL => WPST_SDIF_COUNTRY_CODE_NAMIBIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_NEPAL_LABEL => WPST_SDIF_COUNTRY_CODE_NEPAL_VALUE
           ,WPST_SDIF_COUNTRY_CODE_NEW_ZEALAND_LABEL => WPST_SDIF_COUNTRY_CODE_NEW_ZEALAND_VALUE
           ,WPST_SDIF_COUNTRY_CODE_NICARAGUA_LABEL => WPST_SDIF_COUNTRY_CODE_NICARAGUA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_NIGER_LABEL => WPST_SDIF_COUNTRY_CODE_NIGER_VALUE
           ,WPST_SDIF_COUNTRY_CODE_NIGERIA_LABEL => WPST_SDIF_COUNTRY_CODE_NIGERIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_NORWAY_LABEL => WPST_SDIF_COUNTRY_CODE_NORWAY_VALUE
           ,WPST_SDIF_COUNTRY_CODE_OMAN_LABEL => WPST_SDIF_COUNTRY_CODE_OMAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_PAKISTAN_LABEL => WPST_SDIF_COUNTRY_CODE_PAKISTAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_PANAMA_LABEL => WPST_SDIF_COUNTRY_CODE_PANAMA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_PAPAU_NEW_GUINEA_LABEL => WPST_SDIF_COUNTRY_CODE_PAPAU_NEW_GUINEA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_PARAGUAY_LABEL => WPST_SDIF_COUNTRY_CODE_PARAGUAY_VALUE
           ,WPST_SDIF_COUNTRY_CODE_PEOPLES_REP_OF_CHINA_LABEL => WPST_SDIF_COUNTRY_CODE_PEOPLES_REP_OF_CHINA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_PEOPLES_REP_OF_CONGO_LABEL => WPST_SDIF_COUNTRY_CODE_PEOPLES_REP_OF_CONGO_VALUE
           ,WPST_SDIF_COUNTRY_CODE_PERU_LABEL => WPST_SDIF_COUNTRY_CODE_PERU_VALUE
           ,WPST_SDIF_COUNTRY_CODE_PHILIPPINES_LABEL => WPST_SDIF_COUNTRY_CODE_PHILIPPINES_VALUE
           ,WPST_SDIF_COUNTRY_CODE_POLAND_LABEL => WPST_SDIF_COUNTRY_CODE_POLAND_VALUE
           ,WPST_SDIF_COUNTRY_CODE_PORTUGAL_LABEL => WPST_SDIF_COUNTRY_CODE_PORTUGAL_VALUE
           ,WPST_SDIF_COUNTRY_CODE_PUERTO_RICO_LABEL => WPST_SDIF_COUNTRY_CODE_PUERTO_RICO_VALUE
           ,WPST_SDIF_COUNTRY_CODE_QATAR_LABEL => WPST_SDIF_COUNTRY_CODE_QATAR_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ROMANIA_LABEL => WPST_SDIF_COUNTRY_CODE_ROMANIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_RUSSIA_LABEL => WPST_SDIF_COUNTRY_CODE_RUSSIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_RWANDA_LABEL => WPST_SDIF_COUNTRY_CODE_RWANDA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SAN_MARINO_LABEL => WPST_SDIF_COUNTRY_CODE_SAN_MARINO_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SAUDI_ARABIA_LABEL => WPST_SDIF_COUNTRY_CODE_SAUDI_ARABIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SENEGAL_LABEL => WPST_SDIF_COUNTRY_CODE_SENEGAL_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SEYCHELLES_LABEL => WPST_SDIF_COUNTRY_CODE_SEYCHELLES_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SIERRA_LEONE_LABEL => WPST_SDIF_COUNTRY_CODE_SIERRA_LEONE_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SINGAPORE_LABEL => WPST_SDIF_COUNTRY_CODE_SINGAPORE_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SLOVENIA_LABEL => WPST_SDIF_COUNTRY_CODE_SLOVENIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SOLOMON_ISLANDS_LABEL => WPST_SDIF_COUNTRY_CODE_SOLOMON_ISLANDS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SOMALIA_LABEL => WPST_SDIF_COUNTRY_CODE_SOMALIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SOUTH_AFRICA_LABEL => WPST_SDIF_COUNTRY_CODE_SOUTH_AFRICA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SPAIN_LABEL => WPST_SDIF_COUNTRY_CODE_SPAIN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SRI_LANKA_LABEL => WPST_SDIF_COUNTRY_CODE_SRI_LANKA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ST_VINCENT_AND_THE_GRENADINES_LABEL => WPST_SDIF_COUNTRY_CODE_ST_VINCENT_AND_THE_GRENADINES_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SUDAN_LABEL => WPST_SDIF_COUNTRY_CODE_SUDAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SURINAM_LABEL => WPST_SDIF_COUNTRY_CODE_SURINAM_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SWAZILAND_LABEL => WPST_SDIF_COUNTRY_CODE_SWAZILAND_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SWEDEN_LABEL => WPST_SDIF_COUNTRY_CODE_SWEDEN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SWITZERLAND_LABEL => WPST_SDIF_COUNTRY_CODE_SWITZERLAND_VALUE
           ,WPST_SDIF_COUNTRY_CODE_SYRIA_LABEL => WPST_SDIF_COUNTRY_CODE_SYRIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_TADJIKISTAN_LABEL => WPST_SDIF_COUNTRY_CODE_TADJIKISTAN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_TANZANIA_LABEL => WPST_SDIF_COUNTRY_CODE_TANZANIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_THAILAND_LABEL => WPST_SDIF_COUNTRY_CODE_THAILAND_VALUE
           ,WPST_SDIF_COUNTRY_CODE_THE_NETHERLANDS_LABEL => WPST_SDIF_COUNTRY_CODE_THE_NETHERLANDS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_TOGO_LABEL => WPST_SDIF_COUNTRY_CODE_TOGO_VALUE
           ,WPST_SDIF_COUNTRY_CODE_TONGA_LABEL => WPST_SDIF_COUNTRY_CODE_TONGA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_TRINIDAD_AND_TOBAGO_LABEL => WPST_SDIF_COUNTRY_CODE_TRINIDAD_AND_TOBAGO_VALUE
           ,WPST_SDIF_COUNTRY_CODE_TUNISIA_LABEL => WPST_SDIF_COUNTRY_CODE_TUNISIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_TURKEY_LABEL => WPST_SDIF_COUNTRY_CODE_TURKEY_VALUE
           ,WPST_SDIF_COUNTRY_CODE_UGANDA_LABEL => WPST_SDIF_COUNTRY_CODE_UGANDA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_UKRAINE_LABEL => WPST_SDIF_COUNTRY_CODE_UKRAINE_VALUE
           ,WPST_SDIF_COUNTRY_CODE_UNION_OF_MYANMAR_LABEL => WPST_SDIF_COUNTRY_CODE_UNION_OF_MYANMAR_VALUE
           ,WPST_SDIF_COUNTRY_CODE_UNITED_ARAB_EMIRATES_LABEL => WPST_SDIF_COUNTRY_CODE_UNITED_ARAB_EMIRATES_VALUE
           ,WPST_SDIF_COUNTRY_CODE_UNITED_STATES_OF_AMERICA_LABEL => WPST_SDIF_COUNTRY_CODE_UNITED_STATES_OF_AMERICA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_URUGUAY_LABEL => WPST_SDIF_COUNTRY_CODE_URUGUAY_VALUE
           ,WPST_SDIF_COUNTRY_CODE_VANUATU_LABEL => WPST_SDIF_COUNTRY_CODE_VANUATU_VALUE
           ,WPST_SDIF_COUNTRY_CODE_VENEZUELA_LABEL => WPST_SDIF_COUNTRY_CODE_VENEZUELA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_VIETNAM_LABEL => WPST_SDIF_COUNTRY_CODE_VIETNAM_VALUE
           ,WPST_SDIF_COUNTRY_CODE_VIRGIN_ISLANDS_LABEL => WPST_SDIF_COUNTRY_CODE_VIRGIN_ISLANDS_VALUE
           ,WPST_SDIF_COUNTRY_CODE_WESTERN_SAMOA_LABEL => WPST_SDIF_COUNTRY_CODE_WESTERN_SAMOA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_YEMEN_LABEL => WPST_SDIF_COUNTRY_CODE_YEMEN_VALUE
           ,WPST_SDIF_COUNTRY_CODE_YUGOSLAVIA_LABEL => WPST_SDIF_COUNTRY_CODE_YUGOSLAVIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ZAIRE_LABEL => WPST_SDIF_COUNTRY_CODE_ZAIRE_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ZAMBIA_LABEL => WPST_SDIF_COUNTRY_CODE_ZAMBIA_VALUE
           ,WPST_SDIF_COUNTRY_CODE_ZIMBABWE_LABEL => WPST_SDIF_COUNTRY_CODE_ZIMBABWE_VALUE

        )) ;

        $countrycode->set_readonly($geography == WPST_US_ONLY) ;

        $this->add_element($countrycode) ;

        $regioncode = new FEListBox("Region Code", true, "200px");
        $regioncode->set_list_data(array(
             WPST_SDIF_REGION_CODE_REGION_1_LABEL => WPST_SDIF_REGION_CODE_REGION_1_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_2_LABEL => WPST_SDIF_REGION_CODE_REGION_2_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_3_LABEL => WPST_SDIF_REGION_CODE_REGION_3_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_4_LABEL => WPST_SDIF_REGION_CODE_REGION_4_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_5_LABEL => WPST_SDIF_REGION_CODE_REGION_5_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_6_LABEL => WPST_SDIF_REGION_CODE_REGION_6_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_7_LABEL => WPST_SDIF_REGION_CODE_REGION_7_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_8_LABEL => WPST_SDIF_REGION_CODE_REGION_8_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_9_LABEL => WPST_SDIF_REGION_CODE_REGION_9_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_10_LABEL => WPST_SDIF_REGION_CODE_REGION_10_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_11_LABEL => WPST_SDIF_REGION_CODE_REGION_11_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_12_LABEL => WPST_SDIF_REGION_CODE_REGION_12_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_13_LABEL => WPST_SDIF_REGION_CODE_REGION_13_VALUE
            ,WPST_SDIF_REGION_CODE_REGION_14_LABEL => WPST_SDIF_REGION_CODE_REGION_14_VALUE
        )) ;
        $this->add_element($regioncode) ;

        $swimmeridformat = new FEListBox("Swimmer Id Format", true, "200px");
        $swimmeridformat->set_list_data(array(
             WPST_SDIF_SWIMMER_ID_FORMAT_USA_SWIMMING => WPST_SDIF_SWIMMER_ID_FORMAT_USA_SWIMMING
            ,WPST_SDIF_SWIMMER_ID_FORMAT_SWIMMER_LABEL => WPST_SDIF_SWIMMER_ID_FORMAT_SWIMMER_LABEL
            ,WPST_SDIF_SWIMMER_ID_FORMAT_WPST_ID => WPST_SDIF_SWIMMER_ID_FORMAT_WPST_ID
        )) ;
        $this->add_element($swimmeridformat) ;

        $usenickname = new FEYesNoListBox("Override Firstname with Nickname",
            true, "100px", null, WPST_YES, WPST_NO) ;
        $this->add_element($usenickname) ;

        $useagegroupage = new FEYesNoListBox("Use Age Group Age",
            true, "100px", null, WPST_YES, WPST_NO) ;
        $this->add_element($useagegroupage) ;
    }

    /**
     * This method is called only the first time the form
     * page is hit.  This enables u to query a DB and 
     * pre populate the FormElement objects with data.
     *
     */
    function form_init_data()
    {
        global $userdata ;

        //  Need to pass the WP UserId along to the next step
        $this->set_hidden_element_value("UserId", $userdata->ID) ;

        $p = new SDIFProfile() ;
        $p->loadSDIFProfile() ;
        
        //  Initialize the form fields
        $this->set_element_value("Org Code", $p->getOrgCode()) ;
        $this->set_element_value("Team Code", $p->getTeamCode()) ;
        $this->set_element_value("LSC Code", $p->getLSCCode()) ;
        $this->set_element_value("Country Code", $p->getCountryCode()) ;
        $this->set_element_value("Region Code", $p->getRegionCode()) ;
        $this->set_element_value("Swimmer Id Format", $p->getSwimmerIdFormat()) ;
        $this->set_element_value("Override Firstname with Nickname", $p->getUseNickName()) ;
        $this->set_element_value("Use Age Group Age", $p->getUseAgeGroupAge()) ;
    }

    /**
     * This is the method that builds the layout of where the
     * FormElements will live.  You can lay it out any way
     * you like.
     *
     */
    function form_content()
    {
        $table = html_table($this->_width, 0, 4) ;

        $table->add_row($this->element_label("Org Code"),
            $this->element_form("Org Code")) ;

        $table->add_row($this->element_label("Team Code"),
            $this->element_form("Team Code")) ;

        $table->add_row($this->element_label("LSC Code"),
            $this->element_form("LSC Code")) ;

        $table->add_row($this->element_label("Country Code"),
            $this->element_form("Country Code")) ;

        $table->add_row($this->element_label("Region Code"),
            $this->element_form("Region Code")) ;

        $table->add_row($this->element_label("Swimmer Id Format"),
            $this->element_form("Swimmer Id Format")) ;

        $table->add_row($this->element_label("Override Firstname with Nickname"),
            $this->element_form("Override Firstname with Nickname")) ;

        $table->add_row($this->element_label("Use Age Group Age"),
            $this->element_form("Use Age Group Age")) ;

        $this->add_form_block(null, $table) ;
    }

    /**
     * This method gets called after the FormElement data has
     * passed the validation.  This enables you to validate the
     * data against some backend mechanism, say a DB.
     *
     */
    function form_backend_validation()
    {
        $valid = true ;

        //  First two characters of Team Code must
        //  match the LSC code

        $o = $this->get_element_value("Org Code") ;
        $t = $this->get_element_value("Team Code") ;
        $l = $this->get_element_value("LSC Code") ;
        $c = $this->get_element_value("Country Code") ;
        $r = $this->get_element_value("Region Code") ;
        $f = $this->get_element_value("Swimmer Id Format") ;

        if (substr($t, 0, 2) != $l)
        {
            $this->add_error("Team Code", "First two characters of Team Code must match LSC Code.") ;
            $valid = false ;
        }
        
        if ($c != $c)
        {
            $this->add_error("Country Code", "Country Code is inconsistent with team profile.") ;
            $valid = false ;
        }
        
	    return $valid ;
    }

    /**
     * This method is called ONLY after ALL validation has
     * passed.  This is the method that allows you to 
     * do something with the data, say insert/update records
     * in the DB.
     */
    function form_action()
    {
        $p = new SDIFProfile() ;

        $p->setOrgCode($this->get_element_value("Org Code")) ;
        $p->setTeamCode($this->get_element_value("Team Code")) ;
        $p->setLSCCode($this->get_element_value("LSC Code")) ;
        $p->setCountryCode($this->get_element_value("Country Code")) ;
        $p->setRegionCode($this->get_element_value("Region Code")) ;
        $p->setSwimmerIdFormat($this->get_element_value("Swimmer Id Format")) ;
        $p->setUseNickName($this->get_element_value("Override Firstname with Nickname")) ;
        $p->setUseAgeGroupAge($this->get_element_value("Use Age Group Age")) ;

        $p->updateSDIFProfile() ;

        $this->set_action_message('Swim Team SDIF profile updated.') ;

        return true ;
    }

    /**
     * Build success container
     *
     * @return container
     */
    function form_success()
    {
        $container = container() ;
        $container->add($this->_action_message) ;

        return $container ;
    }
}
?>
